Repository modern-library-how/how.js, pull requests merged in 2025-03, with the labels that each got.

#10 Feat/#4 is odd
  src/__tests__/number/.gitkeep
  src/__tests__/number/isOdd.test.ts
  src/number/.gitkeep
  src/number/isOdd.ts
Labels: new feature

#13 Feat/#9 filterNumber
  src/__tests__/number/filterNumber.test.ts
  src/number/filterNumber.ts
Labels: new feature

#12 Feat/#6 clamp 함수 구현 및 테스트 코드 작성
  src/__tests__/function/.gitkeep
  src/__tests__/function/clamp.test.ts
  src/function/.gitkeep
  src/function/clamp.ts
Labels: new feature

#21 Feat/#7 subtractPercentage
  src/__tests__/function/subtractPercentage.test.ts
  src/function/subtractPercentage.ts
Labels: new feature

#22 Feat/#16 add percentage
  src/__tests__/function/addPercentage.test.ts
  src/function/addPercentage.ts
Labels: new feature

#23 Feat/#17 remove whitespace
  src/__tests__/function/removeWhitespace.test.ts
  src/function/removeWhitespace.ts
Labels: new feature

#32 Feat/#30 chunkString, Feat/#14 getSubsets
  src/__tests__/array/getSubsets.test.ts
  src/__tests__/string/chunkString.test.ts
  src/array/getSubsets.ts
  src/string/chunkString.ts
Labels: new feature

#35 Feat/#27 findMostFrequent
  src/__tests__/array/findMostFrequent.test.ts
  src/array/findMostFrequent.ts
Labels: new feature

#37 Feat/#29 findNth
  src/__tests__/array/findNth.test.ts
  src/array/findNth.ts
Labels: new feature

#38 Feat/#31 sortObject
  src/__tests__/object/sortObject.test.ts
  src/object/sortObject.ts
Labels: new feature

#24 Feat/#18 is empty
  src/__tests__/function/isEmpty.test.ts
  src/function/isEmpty.ts
Labels: new feature

#25 Feat/#19 deep clone
  src/__tests__/function/deepClone.test.ts
  src/function/deepClone.ts
Labels: new feature

#39 Feat/#26 findAllIndex
  src/__tests__/array/findAllIndex.test.ts
  src/array/findAllIndex.ts
Labels: new feature

#43 Feat/#42 is sorted
  src/__tests__/array/isSorted.test.ts
  src/array/isSorted.ts
Labels: new feature

#55 Docs ts doc 주석 작성
  src/array/findAllIndex.ts
  src/array/findMostFrequent.ts
  src/array/findNearest.ts
  src/array/findNth.ts
  src/array/getSubsets.ts
  src/array/isSorted.ts
  src/object/omit.ts
  src/object/sortObject.ts
  src/string/chunkString.ts
Labels: documentation

#56 docs function, number 타입 utility ts-docs 작성
  src/function/addPercentage.ts
  src/function/clamp.ts
  src/function/deepClone.ts
  src/function/isEmpty.ts
  src/function/pipe.ts
  src/function/removeWhitespace.ts
  src/function/subtractPercentage.ts
  src/number/filterNumber.ts
  src/number/isEven.ts
  src/number/isOdd.ts
Labels: documentation

#63 bugfix[#62] 배포 버그 해결
  .npmignore
  package.json
Labels: bug
